from PyPDF2 import PdfReader, PdfMerger, PdfWriter                                                                                                                                                                                   
                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                     
def merge(pdf1, pdf2, out):                                                                                                                                                                                                          
    reader1 = PdfReader(pdf1)                                                                                                                                                                                                        
    reader2 = PdfReader(pdf2)                                                                                                                                                                                                        
    file_merge = PdfMerger()                                                                                                                                                                                                         
    file_merge.append(reader2)                                                                                                                                                                                                       
    file_merge.append(reader1, pages=tuple(range(len(reader1.pages), len(reader1.pages) + len(reader2.pages))))                                                                                                                      
    file_merge.write(out)                                                                                                                                                                                                            
                                                                                                                                                                                                                                     
def merge_all(pdfs, out="merge.pdf"):                                                                                                                                                                                                
    merger = PdfMerger()                                                                                                                                                                                                             
    start_page = 0                                                                                                                                                                                                                   
    for pdf in pdfs:                                                                                                                                                                                                                 
        reader = PdfReader(pdf)                                                                                                                                                                                                      
        # merger.append(reader, pages=tuple(range(start_page, start_page + len(reader.pages))))                                                                                                                                      
        merger.append(reader)                                                                                                                                                                                                        
        start_page += len(reader.pages)                                                                                                                                                                                              
    merger.write(out)                                                                                                                                                                                                                
                                                                                                                                                                                                                                     
def cutPages(pdf, start_page=0, end_page=10000, out="cut.pdf"):                                                                                                                                                                      
    reader = PdfReader(pdf)                                                                                                                                                                                                          
    count = len(reader.pages)                                                                                                                                                                                                        
    print("count is: %d " % count)                                                                                                                                                                                                   
    if end_page > count:                                                                                                                                                                                                             
        end_page = count                                                                                                                                                                                                             
    pdf_writer = PdfWriter()                                                                                                                                                                                                         
    for page in range(start_page,end_page):                                                                                                                                                                                          
        pdf_writer.add_page(reader.pages[page])                                                                                                                                                                                      
    pdf_writer.write(out)                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
cutPages("2022YFB4502000_2023NB.pdf", 1, 176, "0.pdf")                                                                                                                                                                                                                                           

pdfs=["封面.pdf", "0.pdf", "尾页.pdf"]                                                                                                                                                                                   
for pdf in pdfs:                                                                                                                                                                                                                     
    print("pdf is: %s " % pdf)                                                                                                                                                                                                       
                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                     
merge_all(pdfs)